# Generated by Django 3.0.8 on 2020-08-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='movie_id',
            new_name='movieId',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user_id',
            new_name='userId',
        ),
    ]
